export * from './observer.utility'
export * from './resolve.utility'
export * from './entries.utility'
export { assign } from './assign.utility'
export { isFunction } from './isFunction.utility'
export { compose } from './compose.utility'
export { isAsyncFunction } from './isAsyncFunction.utility'
export { mapObject } from './mapObject.utility'
export { set } from './set.utility'
export { merge } from './merge.utility'
export { empty } from './empty.utility'
export { isPlainObject } from './isPlainObject.utility'
export { flatObject } from './flatObject.utility'
export { isNil } from './isNil.utility'
export { filterObject } from './filterObject.utility'
export { split } from './split.utility'

export const noop = () => {}
